# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FlutterIntegrationExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FlutterIntegrationExample

  flutter_application_path = '../FlutterIntegration_Flutter'
  load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

  install_all_flutter_pods(flutter_application_path)


end
